name: DonorPerks
main: xyz.minestory.donorperks.DonorPerksPlugin
version: 1.0.0
author: Higgins
commands:
  StoryPerk:
    description: Shows the perks for Solar rank
    aliases: []
  NebulaPerk:
    description: Shows the perks for Nebula rank
    aliases: []
  GalacticPerk:
    description: Shows the perks for Galactic rank
    aliases: []
  CosmicPerk:
    description: Shows the perks for Cosmic rank
    aliases: []
  SolarPerk:
    description: Shows the perks for Solar rank
    aliases: []

